package Presupuestos;

//Cesar Julio Beltran - Costos y Presupuestos

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStream;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

public class PanelEjercicioOcho extends javax.swing.JPanel 
{

    float tH = 0.0f;    
    float pe = 0.0f;
    
    public PanelEjercicioOcho() 
    {
        initComponents();
        
        formatoImporte = NumberFormat.getCurrencyInstance();
        formatoNumero = NumberFormat.getNumberInstance();        
        
        gop = new GetOperaciones();        
        vf = new VentanaFormulario(8);    
        
        totalVaria.setEditable(false);
        totalFijo.setEditable(false);
        totalDiarioP.setEditable(false);
        totalDiarioH.setEditable(false);
        totalMensualP.setEditable(false);
        totalMensualH.setEditable(false); 
        
        setBloquear();   
        setInicializar();          
    }
    
    public void setInicializar()
    {
        textPan.setText("0.50");
        textCarne.setText("1.4");
        otroVaria.setText("0.5");
        textSueldo.setText("10000");
        otroFijo.setText("2000");
        textPrecio.setText("5.50");       
    }
    
    public void setBorrar()
    {
        textPan.setText(null);
        textCarne.setText(null);
        otroVaria.setText(null);
        textSueldo.setText(null);
        otroFijo.setText(null);
        textPrecio.setText(null);
        totalVaria.setText(null);
        totalFijo.setText(null);
        totalDiarioP.setText(null);
        totalDiarioH.setText(null);
        totalMensualP.setText(null);
        totalMensualH.setText(null);
    }
    
    public void setEditar()
    {
        textPan.setEditable(true);
        textCarne.setEditable(true);
        otroVaria.setEditable(true);
        textSueldo.setEditable(true);
        otroFijo.setEditable(true);
        textPrecio.setEditable(true);  
    }
    
    public void setBloquear()
    {
        textPan.setEditable(false);
        textCarne.setEditable(false);
        otroVaria.setEditable(false);
        textSueldo.setEditable(false);
        otroFijo.setEditable(false);
        textPrecio.setEditable(false);   
    }
    
    public void setOperaciones()
    {
        float tCV = 0.0f;
        
        tCV = Float.parseFloat(textPan.getText()) + Float.parseFloat(textCarne.getText()) + Float.parseFloat(otroVaria.getText());
    
        totalVaria.setText(formatoImporte.format(tCV));
        
        float tCF = 0.0f;
        
        tCF = Float.parseFloat(textSueldo.getText()) + Float.parseFloat(otroFijo.getText());
    
        totalFijo.setText(formatoImporte.format(tCF));        
    }
    
    public void setA()
    {
        float tCV = 0.0f;
        
        tCV = Float.parseFloat(textPan.getText()) + Float.parseFloat(textCarne.getText()) + Float.parseFloat(otroVaria.getText());
    
        totalVaria.setText(formatoImporte.format(tCV));
        
        float tCF = 0.0f;
        
        tCF = Float.parseFloat(textSueldo.getText()) + Float.parseFloat(otroFijo.getText());
    
        totalFijo.setText(formatoImporte.format(tCF));          
        
        tH = gop.getEquilibrioUnidad(tCF, tCV, Float.parseFloat(textPrecio.getText()));
    
        totalDiarioH.setText(formatoNumero.format(tH));
        
        float mc = 0.0f;
        
        mc = gop.getMargenContribucion(Float.parseFloat(textPrecio.getText()), tCV);
        
        mc /= 100;
        
        pe = tCF / mc;
        
        totalDiarioP.setText(formatoImporte.format(pe));
    }
    
    public void setB()
    {
        float tHM = 0.0f;
        
        tHM = tH / 30;
        
        totalMensualH.setText(formatoNumero.format(tHM));
        
        float tPM = 0.0f;
        
        tPM = pe / 30;
        
        totalMensualP.setText(formatoImporte.format(tPM));
    }

    public void setDejarVer()
    {
        verFormulario.setSelected(false);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonAbrirArchivo = new javax.swing.JButton();
        verFormulario = new javax.swing.JToggleButton();
        botonEditar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonIniciar = new javax.swing.JButton();
        botonCalcularS = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textSueldo = new javax.swing.JTextField();
        otroFijo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textPan = new javax.swing.JTextField();
        textCarne = new javax.swing.JTextField();
        otroVaria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalFijo = new javax.swing.JTextField();
        totalVaria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totalDiarioP = new javax.swing.JTextField();
        totalMensualP = new javax.swing.JTextField();
        totalMensualH = new javax.swing.JTextField();
        totalDiarioH = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ejercicio 8");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 160, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 0, 40, 40);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 40);

        jToolBar1.setRollover(true);

        botonAbrirArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abrirPDF.png"))); // NOI18N
        botonAbrirArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAbrirArchivo.setFocusable(false);
        botonAbrirArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAbrirArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAbrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAbrirArchivoMouseClicked(evt);
            }
        });
        jToolBar1.add(botonAbrirArchivo);

        verFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        verFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verFormulario.setFocusable(false);
        verFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verFormulario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verFormulario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                verFormularioItemStateChanged(evt);
            }
        });
        jToolBar1.add(verFormulario);

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.setFocusable(false);
        botonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonEditar);

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrar.setFocusable(false);
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBorrarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonBorrar);

        botonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar.png"))); // NOI18N
        botonIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIniciar.setFocusable(false);
        botonIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIniciarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonIniciar);

        botonCalcularS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calcular.png"))); // NOI18N
        botonCalcularS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcularS.setFocusable(false);
        botonCalcularS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCalcularS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCalcularS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCalcularSMouseClicked(evt);
            }
        });
        jToolBar1.add(botonCalcularS);

        add(jToolBar1);
        jToolBar1.setBounds(0, 40, 730, 30);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(0, 430, 730, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hamburguesas");
        add(jLabel3);
        jLabel3.setBounds(0, 74, 730, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Costos fijos:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 0, 280, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 280, 30);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sueldo de cocina");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel9);
        jLabel9.setBounds(0, 0, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Otros:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel7);
        jLabel7.setBounds(0, 30, 180, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 30, 180, 60);

        textSueldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textSueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSueldoKeyTyped(evt);
            }
        });
        jPanel3.add(textSueldo);
        textSueldo.setBounds(180, 30, 100, 30);

        otroFijo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        otroFijo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        otroFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otroFijoKeyTyped(evt);
            }
        });
        jPanel3.add(otroFijo);
        otroFijo.setBounds(180, 60, 100, 30);

        add(jPanel3);
        jPanel3.setBounds(380, 130, 280, 90);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Costos variables:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel10);
        jLabel10.setBounds(0, 0, 280, 30);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, 0, 280, 30);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pan:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel11);
        jLabel11.setBounds(0, 0, 180, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Carne (por hamburguesa):");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel12);
        jLabel12.setBounds(0, 30, 180, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Otros:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel15);
        jLabel15.setBounds(0, 60, 180, 30);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(0, 30, 180, 90);

        textPan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textPan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textPan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPanKeyTyped(evt);
            }
        });
        jPanel6.add(textPan);
        textPan.setBounds(180, 30, 100, 30);

        textCarne.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textCarne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textCarne.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCarneKeyTyped(evt);
            }
        });
        jPanel6.add(textCarne);
        textCarne.setBounds(180, 60, 100, 30);

        otroVaria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        otroVaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        otroVaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otroVariaKeyTyped(evt);
            }
        });
        jPanel6.add(otroVaria);
        otroVaria.setBounds(180, 90, 100, 30);

        add(jPanel6);
        jPanel6.setBounds(50, 110, 280, 120);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total:");
        add(jLabel13);
        jLabel13.setBounds(160, 240, 70, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Punto de equilibrio mensual:");
        add(jLabel14);
        jLabel14.setBounds(340, 350, 250, 30);

        totalFijo.setBackground(new java.awt.Color(204, 255, 204));
        totalFijo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalFijo);
        totalFijo.setBounds(560, 240, 100, 30);

        totalVaria.setBackground(new java.awt.Color(204, 255, 204));
        totalVaria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalVaria);
        totalVaria.setBounds(230, 240, 100, 30);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(160, 360, 110, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Total:");
        add(jLabel16);
        jLabel16.setBounds(500, 240, 60, 30);

        textPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPrecioKeyTyped(evt);
            }
        });
        add(textPrecio);
        textPrecio.setBounds(90, 310, 100, 30);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("hamburguesas");
        add(jLabel23);
        jLabel23.setBounds(590, 380, 90, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Precio de venta:");
        add(jLabel17);
        jLabel17.setBounds(70, 280, 110, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Punto de equilibrio diario:");
        add(jLabel18);
        jLabel18.setBounds(340, 280, 250, 30);

        totalDiarioP.setBackground(new java.awt.Color(255, 255, 0));
        totalDiarioP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalDiarioP);
        totalDiarioP.setBounds(340, 310, 100, 30);

        totalMensualP.setBackground(new java.awt.Color(255, 255, 0));
        totalMensualP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalMensualP);
        totalMensualP.setBounds(340, 380, 100, 30);

        totalMensualH.setBackground(new java.awt.Color(255, 255, 0));
        totalMensualH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalMensualH);
        totalMensualH.setBounds(490, 380, 100, 30);

        totalDiarioH.setBackground(new java.awt.Color(255, 255, 0));
        totalDiarioH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalDiarioH);
        totalDiarioH.setBounds(490, 310, 100, 30);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("$");
        add(jLabel24);
        jLabel24.setBounds(70, 310, 20, 30);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("hamburguesas");
        add(jLabel25);
        jLabel25.setBounds(590, 310, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirArchivoMouseClicked
        try
        {
            //Creamos un archivo en la carpeta temporal de tu sistema operativo
            File temp = new File(System.getProperty("java.io.tmpdir") + "Ejercicios.pdf");
            
            //Creamos un flujo de entrada al cual asignamos el valor del PDF que esta dentro del JAR
            InputStream flujoEntrada = this.getClass().getResourceAsStream("/Archivos/Ejercicios_del_sistema.pdf");
            
            //Creamos un flujo de salida para poder escribir sobre el archivo temporal
            FileOutputStream flujoSalida = new FileOutputStream(temp);
            //Preparamos el temp para que se llene de la informacion de PDF dentro del jar
            FileWriter fw = new FileWriter(temp);
            //Creamos un arreglo de bytes generico que soporte un gran tamano 1KB * 512 B --> se usa para todo tipo de archivo  
            byte[] buffer = new byte[1024*512];
 
            int control; //para contar posiciones de byte
 
            //Mientras haya bytes por leer se ejecuta este bucle
            while ((control = flujoEntrada.read(buffer)) != -1){
                flujoSalida.write(buffer, 0, control);
            }
 
            //Cerramos y guardamos el archivo creado
            fw.close();
            flujoSalida.close();
            flujoEntrada.close();
 
            //Ahora ya tenemos en temp todo tu PDF descomprimido y lo podemos abrir
            Desktop.getDesktop().open(temp);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Existe un error: " + e,"Ejercicios pdf", 2);
        }
    }//GEN-LAST:event_botonAbrirArchivoMouseClicked

    private void verFormularioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_verFormularioItemStateChanged
        if(verFormulario.isSelected())
        {
            vf.setVisible(true);
        }
        else
        {
            vf.dispose();
        }
    }//GEN-LAST:event_verFormularioItemStateChanged

    private void textPanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPanKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textPan.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textPanKeyTyped

    private void textCarneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCarneKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textCarne.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textCarneKeyTyped

    private void otroVariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otroVariaKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && otroVaria.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_otroVariaKeyTyped

    private void textSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSueldoKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textSueldo.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textSueldoKeyTyped

    private void otroFijoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otroFijoKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && otroFijo.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_otroFijoKeyTyped

    private void textPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrecioKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textPrecio.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textPrecioKeyTyped

    private void botonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseClicked
        setEditar();
        totalVaria.setText(null);
        totalFijo.setText(null);
        totalDiarioP.setText(null);
        totalDiarioH.setText(null);
        totalMensualP.setText(null);
        totalMensualH.setText(null);
    }//GEN-LAST:event_botonEditarMouseClicked

    private void botonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMouseClicked
        setBorrar();
        setBloquear();
    }//GEN-LAST:event_botonBorrarMouseClicked

    private void botonIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarMouseClicked
        setBorrar();
        setInicializar();
        setBloquear();
    }//GEN-LAST:event_botonIniciarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(textPan.getText().equals("") || textCarne.getText().equals("") || otroVaria.getText().equals("") ||
                textSueldo.getText().equals("") || textPrecio.getText().equals("") || otroFijo.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Se han detectado valores nulos \n","Verifique los datos ingresados", 0);
        else
        {
            try
            {
                setOperaciones();
                setA();
                setB();
                setBloquear();  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error, se han detectado valores nulos: \n" + e ,"Verifique los datos ingresados", 0);
            }
        }            
    }//GEN-LAST:event_jButton1MouseClicked

    private void botonCalcularSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCalcularSMouseClicked
        if(textPan.getText().equals("") || textCarne.getText().equals("") || otroVaria.getText().equals("") ||
                textSueldo.getText().equals("") || textPrecio.getText().equals("") || otroFijo.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Se han detectado valores nulos \n","Verifique los datos ingresados", 0);
        else
        {
            try
            {
                setOperaciones();
                setA();
                setB();
                setBloquear();  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error, se han detectado valores nulos: \n" + e ,"Verifique los datos ingresados", 0);
            }
        }    
    }//GEN-LAST:event_botonCalcularSMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbrirArchivo;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCalcularS;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField otroFijo;
    private javax.swing.JTextField otroVaria;
    private javax.swing.JTextField textCarne;
    private javax.swing.JTextField textPan;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textSueldo;
    private javax.swing.JTextField totalDiarioH;
    private javax.swing.JTextField totalDiarioP;
    private javax.swing.JTextField totalFijo;
    private javax.swing.JTextField totalMensualH;
    private javax.swing.JTextField totalMensualP;
    private javax.swing.JTextField totalVaria;
    private javax.swing.JToggleButton verFormulario;
    // End of variables declaration//GEN-END:variables
    GetOperaciones gop;
    NumberFormat formatoImporte;
    NumberFormat formatoNumero;    
    private VentanaFormulario vf;
}
