package Presupuestos;

//Cesar Julio Beltran - Costos y Presupuestos

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStream;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;


public class PanelEjercicioNueve extends javax.swing.JPanel 
{
    float cv = 0.0f;
    float cf = 0.0f;    
    
    public PanelEjercicioNueve() 
    {
        initComponents();
        
        formatoImporte = NumberFormat.getCurrencyInstance();
        formatoNumero = NumberFormat.getNumberInstance();
        
        gop = new GetOperaciones();
        vf = new VentanaFormulario(9);        
        
        totalVaria.setEditable(false);
        totalFijo.setEditable(false);
        totalAumento.setEditable(false);
        totalPunto.setEditable(false);
        totalCaja.setEditable(false);
        
        spinnerTasa.setEditor(new JSpinner.DefaultEditor(spinnerTasa));
        spinnerAumento.setEditor(new JSpinner.DefaultEditor(spinnerAumento));
        
        setBloquear();   
        setInicializar();
    }
    
    public void setInicializar()
    {
        textCosto.setText("20");
        textGasto.setText("4");
        textVenta.setText("1600000");
        textAdm.setText("2800000");
        textPrecio.setText("40");
        textVolumen.setText("390000");
        spinnerTasa.setValue(35);
        spinnerAumento.setValue(15);        
    }
    
    public void setBorrar()
    {
        textCosto.setText(null);
        textGasto.setText(null);
        textVenta.setText(null);
        textAdm.setText(null);
        textPrecio.setText(null);
        textVolumen.setText(null);
        spinnerTasa.setValue(0);
        spinnerAumento.setValue(0);
        totalVaria.setText(null);
        totalFijo.setText(null);
        totalAumento.setText(null);
        totalPunto.setText(null);
        totalCaja.setText(null);   
    }
    
    public void setEditar()
    {
        textCosto.setEditable(true);
        textGasto.setEditable(true);
        textVenta.setEditable(true);
        textAdm.setEditable(true);
        textPrecio.setEditable(true);
        textVolumen.setEditable(true);
        spinnerTasa.setEnabled(true);
        spinnerAumento.setEnabled(true);      
    }
    
    public void setBloquear()
    {
        textCosto.setEditable(false);
        textGasto.setEditable(false);
        textVenta.setEditable(false);
        textAdm.setEditable(false);
        textPrecio.setEditable(false);
        textVolumen.setEditable(false);
        spinnerTasa.setEnabled(false);
        spinnerAumento.setEnabled(false);   
    }
    
    public void setOperaciones()
    {
        cv = Float.parseFloat(textCosto.getText()) + Float.parseFloat(textGasto.getText());
        
        totalVaria.setText(formatoImporte.format(cv));

        cf = Float.parseFloat(textVenta.getText()) + Float.parseFloat(textAdm.getText());
        
        totalFijo.setText(formatoImporte.format(cf));
        
        int vl = 0;
        
        vl = (int) (Float.parseFloat(textVolumen.getText()) * Float.parseFloat(textPrecio.getText()));
        
        totalCaja.setText(formatoImporte.format(vl));
    }

    public void setA()
    {
        float pe = 0.0f;
        
        pe = gop.getEquilibrioUnidad(cf, cv, Float.parseFloat(textPrecio.getText()));
        
        totalPunto.setText(formatoNumero.format(pe));
    }
    
    public void setB()
    {
        float cv = 0.0f;
        
        cv = gop.getCostoVariable( Float.parseFloat(textCosto.getText()),  Float.parseFloat(spinnerAumento.getValue().toString()),  Float.parseFloat(textGasto.getText()));
        
        float mc = 0.0f;
        
        mc = gop.getMargenContribucionActual(cv, Float.parseFloat(textPrecio.getText()));
        
        float np = 0.0f;
        
        np = gop.getNuevoPrecio(cv, mc);
        
        totalAumento.setText(formatoImporte.format(np));
    }
    
    public void setDejarVer()
    {
        verFormulario.setSelected(false);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonAbrirArchivo = new javax.swing.JButton();
        verFormulario = new javax.swing.JToggleButton();
        botonEditar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonInicializar = new javax.swing.JButton();
        botonCalcularS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        textGasto = new javax.swing.JTextField();
        textCosto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalVaria = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textVenta = new javax.swing.JTextField();
        textAdm = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalFijo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textVolumen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalCaja = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        spinnerTasa = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        totalPunto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        spinnerAumento = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        totalAumento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ejercicio 9");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 160, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 0, 40, 40);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 40);

        jToolBar1.setRollover(true);

        botonAbrirArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abrirPDF.png"))); // NOI18N
        botonAbrirArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAbrirArchivo.setFocusable(false);
        botonAbrirArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAbrirArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAbrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAbrirArchivoMouseClicked(evt);
            }
        });
        jToolBar1.add(botonAbrirArchivo);

        verFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        verFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verFormulario.setFocusable(false);
        verFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verFormulario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verFormulario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                verFormularioItemStateChanged(evt);
            }
        });
        jToolBar1.add(verFormulario);

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.setFocusable(false);
        botonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonEditar);

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrar.setFocusable(false);
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBorrarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonBorrar);

        botonInicializar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar.png"))); // NOI18N
        botonInicializar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicializar.setFocusable(false);
        botonInicializar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonInicializar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonInicializar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicializarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonInicializar);

        botonCalcularS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calcular.png"))); // NOI18N
        botonCalcularS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcularS.setFocusable(false);
        botonCalcularS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCalcularS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCalcularS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCalcularSMouseClicked(evt);
            }
        });
        jToolBar1.add(botonCalcularS);

        add(jToolBar1);
        jToolBar1.setBounds(0, 40, 730, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dulces Tory S.A.");
        add(jLabel3);
        jLabel3.setBounds(0, 80, 730, 30);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(0, 430, 730, 20);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        textGasto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textGasto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textGasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textGastoKeyTyped(evt);
            }
        });
        jPanel3.add(textGasto);
        textGasto.setBounds(120, 60, 110, 30);

        textCosto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textCosto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCostoKeyTyped(evt);
            }
        });
        jPanel3.add(textCosto);
        textCosto.setBounds(120, 30, 110, 30);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Costos variables promedio por caja:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 230, 32);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Costo del dulce:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel5);
        jLabel5.setBounds(0, 0, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gastos de venta:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel6);
        jLabel6.setBounds(0, 30, 120, 30);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(0, 30, 120, 60);

        add(jPanel3);
        jPanel3.setBounds(70, 120, 230, 90);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total:");
        add(jLabel7);
        jLabel7.setBounds(480, 220, 60, 30);

        totalVaria.setBackground(new java.awt.Color(204, 255, 204));
        totalVaria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalVaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(totalVaria);
        totalVaria.setBounds(190, 220, 110, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Gastos fijos anuales:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 230, 32);

        textVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textVentaKeyTyped(evt);
            }
        });
        jPanel5.add(textVenta);
        textVenta.setBounds(120, 30, 110, 30);

        textAdm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textAdm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textAdm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAdmKeyTyped(evt);
            }
        });
        jPanel5.add(textAdm);
        textAdm.setBounds(120, 60, 110, 30);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ventas:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel8);
        jLabel8.setBounds(0, 0, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Administrativos:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel9);
        jLabel9.setBounds(0, 30, 120, 30);

        jPanel5.add(jPanel8);
        jPanel8.setBounds(0, 30, 120, 60);

        add(jPanel5);
        jPanel5.setBounds(420, 120, 230, 90);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Total:");
        add(jLabel10);
        jLabel10.setBounds(130, 220, 60, 30);

        totalFijo.setBackground(new java.awt.Color(204, 255, 204));
        totalFijo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalFijo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(totalFijo);
        totalFijo.setBounds(540, 220, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Volumen de ventas esperado por");
        add(jLabel12);
        jLabel12.setBounds(20, 370, 190, 30);

        textVolumen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textVolumenKeyTyped(evt);
            }
        });
        add(textVolumen);
        textVolumen.setBounds(210, 370, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cajas:");
        add(jLabel13);
        jLabel13.setBounds(310, 370, 40, 30);

        totalCaja.setBackground(new java.awt.Color(204, 255, 204));
        totalCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalCaja);
        totalCaja.setBounds(360, 370, 110, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Precio de venta promedio por caja:");
        add(jLabel14);
        jLabel14.setBounds(20, 270, 200, 30);

        textPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPrecioKeyTyped(evt);
            }
        });
        add(textPrecio);
        textPrecio.setBounds(240, 270, 90, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Tasa impositiva:");
        add(jLabel15);
        jLabel15.setBounds(20, 320, 100, 30);
        add(spinnerTasa);
        spinnerTasa.setBounds(120, 320, 50, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Punto de equilibrio:");
        add(jLabel16);
        jLabel16.setBounds(360, 270, 130, 30);

        totalPunto.setBackground(new java.awt.Color(255, 255, 0));
        totalPunto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalPunto);
        totalPunto.setBounds(490, 270, 100, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Nuevo precio por caja con el");
        add(jLabel17);
        jLabel17.setBounds(220, 320, 170, 30);
        add(spinnerAumento);
        spinnerAumento.setBounds(390, 320, 50, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("de aumento:");
        add(jLabel18);
        jLabel18.setBounds(460, 320, 80, 30);

        totalAumento.setBackground(new java.awt.Color(255, 255, 0));
        totalAumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalAumento);
        totalAumento.setBounds(550, 320, 110, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("%");
        add(jLabel19);
        jLabel19.setBounds(170, 320, 20, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("%");
        add(jLabel20);
        jLabel20.setBounds(440, 320, 20, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("$");
        add(jLabel21);
        jLabel21.setBounds(220, 270, 20, 30);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3);
        jSeparator3.setBounds(200, 320, 10, 30);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4);
        jSeparator4.setBounds(350, 270, 10, 30);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(540, 370, 100, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Unidades");
        add(jLabel26);
        jLabel26.setBounds(590, 270, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseClicked
        setEditar();
        totalVaria.setText(null);
        totalFijo.setText(null);
        totalAumento.setText(null);
        totalPunto.setText(null);
        totalCaja.setText(null);        
    }//GEN-LAST:event_botonEditarMouseClicked

    private void botonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMouseClicked
        setBorrar();
        setBloquear();
    }//GEN-LAST:event_botonBorrarMouseClicked

    private void botonInicializarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicializarMouseClicked
        setBorrar();
        setInicializar();
        setBloquear();
    }//GEN-LAST:event_botonInicializarMouseClicked

    private void textCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCostoKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textCosto.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textCostoKeyTyped

    private void textGastoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textGastoKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textGasto.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textGastoKeyTyped

    private void textVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textVentaKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textVenta.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textVentaKeyTyped

    private void textAdmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAdmKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textAdm.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textAdmKeyTyped

    private void textPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrecioKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textPrecio.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textPrecioKeyTyped

    private void textVolumenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textVolumenKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && textVolumen.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_textVolumenKeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(textCosto.getText().equals("") || textGasto.getText().equals("") || textPrecio.getText().equals("") ||
                textVenta.getText().equals("") || textAdm.getText().equals("") || textVolumen.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Se han detectado valores nulos \n","Verifique los datos ingresados", 0);
        else
        {
            try
            {
                setOperaciones();
                setA();
                setB();
                setBloquear();  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error, se han detectado valores nulos: \n" + e ,"Verifique los datos ingresados", 0);
            }
        }        
    }//GEN-LAST:event_jButton1MouseClicked

    private void botonCalcularSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCalcularSMouseClicked
        if(textCosto.getText().equals("") || textGasto.getText().equals("") || textPrecio.getText().equals("") ||
                textVenta.getText().equals("") || textAdm.getText().equals("") || textVolumen.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Se han detectado valores nulos \n","Verifique los datos ingresados", 0);
        else
        {
            try
            {
                setOperaciones();
                setA();
                setB();
                setBloquear();  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error, se han detectado valores nulos: \n" + e ,"Verifique los datos ingresados", 0);
            }
        }        
    }//GEN-LAST:event_botonCalcularSMouseClicked

    private void botonAbrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirArchivoMouseClicked
        try
        {
            //Creamos un archivo en la carpeta temporal de tu sistema operativo
            File temp = new File(System.getProperty("java.io.tmpdir") + "Ejercicios.pdf");
            
            //Creamos un flujo de entrada al cual asignamos el valor del PDF que esta dentro del JAR
            InputStream flujoEntrada = this.getClass().getResourceAsStream("/Archivos/Ejercicios_del_sistema.pdf");
            
            //Creamos un flujo de salida para poder escribir sobre el archivo temporal
            FileOutputStream flujoSalida = new FileOutputStream(temp);
            //Preparamos el temp para que se llene de la informacion de PDF dentro del jar
            FileWriter fw = new FileWriter(temp);
            //Creamos un arreglo de bytes generico que soporte un gran tamano 1KB * 512 B --> se usa para todo tipo de archivo  
            byte[] buffer = new byte[1024*512];
 
            int control; //para contar posiciones de byte
 
            //Mientras haya bytes por leer se ejecuta este bucle
            while ((control = flujoEntrada.read(buffer)) != -1){
                flujoSalida.write(buffer, 0, control);
            }
 
            //Cerramos y guardamos el archivo creado
            fw.close();
            flujoSalida.close();
            flujoEntrada.close();
 
            //Ahora ya tenemos en temp todo tu PDF descomprimido y lo podemos abrir
            Desktop.getDesktop().open(temp);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Existe un error: " + e,"Ejercicios pdf", 2);
        }
    }//GEN-LAST:event_botonAbrirArchivoMouseClicked

    private void verFormularioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_verFormularioItemStateChanged
        if(verFormulario.isSelected())
        {
            vf.setVisible(true);
        }
        else
        {
            vf.dispose();
        }
    }//GEN-LAST:event_verFormularioItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbrirArchivo;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCalcularS;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonInicializar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner spinnerAumento;
    private javax.swing.JSpinner spinnerTasa;
    private javax.swing.JTextField textAdm;
    private javax.swing.JTextField textCosto;
    private javax.swing.JTextField textGasto;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textVenta;
    private javax.swing.JTextField textVolumen;
    private javax.swing.JTextField totalAumento;
    private javax.swing.JTextField totalCaja;
    private javax.swing.JTextField totalFijo;
    private javax.swing.JTextField totalPunto;
    private javax.swing.JTextField totalVaria;
    private javax.swing.JToggleButton verFormulario;
    // End of variables declaration//GEN-END:variables
    GetOperaciones gop;
    NumberFormat formatoImporte;
    NumberFormat formatoNumero;
    private VentanaFormulario vf;    
}
