package Presupuestos;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStream;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

//Cesar Julio Beltran - Costos y Presupuestos

public class PanelEjercicioSeis extends javax.swing.JPanel 
{

    public PanelEjercicioSeis() 
    {
        initComponents();
        
        gop = new GetOperaciones();        
        vf = new VentanaFormulario(6);  
        
        formatoImporte = NumberFormat.getCurrencyInstance();
        formatoNumero = NumberFormat.getNumberInstance();     
        
        totalMargen.setEditable(false);
        totalNMargen.setEditable(false);
        totalPasajeros.setEditable(false);
        totalNPasajeros.setEditable(false);        
        
        setBloquear();   
        setInicializar();         
    }
    
    public void setInicializar()
    {
        costoSueldo.setText("500");
        costosFijos.setText("40000");
        tarifaUnica.setText("50");
        costoVaria.setText("5");
        viajesSemanales.setText("100");
        viajesNSemanales.setText("50");
        utilidad.setText("25000");
        ganarMensual.setText("10000");        
    }
    
    public void setBorrar()
    {
        costoSueldo.setText(null);
        costosFijos.setText(null);
        tarifaUnica.setText(null);
        costoVaria.setText(null);
        viajesSemanales.setText(null);
        viajesNSemanales.setText(null);
        utilidad.setText(null);
        ganarMensual.setText(null);
        totalMargen.setText(null);
        totalNMargen.setText(null);
        totalPasajeros.setText(null);
        totalNPasajeros.setText(null);
    }
    
    public void setEditar()
    {
        costoSueldo.setEditable(true);
        costosFijos.setEditable(true);
        tarifaUnica.setEditable(true);
        costoVaria.setEditable(true);
        viajesSemanales.setEditable(true);
        viajesNSemanales.setEditable(true);
        utilidad.setEditable(true);
        ganarMensual.setEditable(true);      
    }
    
    public void setBloquear()
    {
        costoSueldo.setEditable(false);
        costosFijos.setEditable(false);
        tarifaUnica.setEditable(false);
        costoVaria.setEditable(false);
        viajesSemanales.setEditable(false);
        viajesNSemanales.setEditable(false);
        utilidad.setEditable(false);
        ganarMensual.setEditable(false);           
    }  
    
    public void setA()
    {
        int viajesMes = 0;
        
        viajesMes = (int) (Integer.parseInt(viajesSemanales.getText()) * 4.3);
        
        float cf = 0.0f;
        
        cf = (Float.parseFloat(costoSueldo.getText()) * viajesMes) + Float.parseFloat(costosFijos.getText());
        
        float mc = 0.0f;
        
        mc = cf + Float.parseFloat(utilidad.getText());
        
        totalMargen.setText(formatoImporte.format(mc));
        
        float mcu = 0.0f;
        
        mcu = Float.parseFloat(tarifaUnica.getText()) - Float.parseFloat(costoVaria.getText());
        
        int paj = 0;
        
        paj = (int) (mc / mcu);
        
        totalPasajeros.setText(formatoNumero.format(paj));
    }
    
    public void setB()
    {
        int viajesMes = 0;
        
        viajesMes = (int) (Integer.parseInt(viajesNSemanales.getText()) * 4.3);
        
        float cf = 0.0f;
        
        cf = (Float.parseFloat(costoSueldo.getText()) * viajesMes) + Float.parseFloat(costosFijos.getText());
        
        float mc = 0.0f;
        
        mc = cf + Float.parseFloat(ganarMensual.getText());
        
        totalNMargen.setText(formatoImporte.format(mc));
        
        float mcu = 0.0f;
        
        mcu = Float.parseFloat(tarifaUnica.getText()) - Float.parseFloat(costoVaria.getText());
        
        int paj = 0;
        
        paj = (int) (mc / mcu);
        
        totalNPasajeros.setText(formatoNumero.format(paj));
    }    

    public void setDejarVer()
    {
        verFormulario.setSelected(false);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonAbrirArchivo = new javax.swing.JButton();
        verFormulario = new javax.swing.JToggleButton();
        botonEditar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonInicializar = new javax.swing.JButton();
        botonCalcularS = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        costoSueldo = new javax.swing.JTextField();
        costosFijos = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tarifaUnica = new javax.swing.JTextField();
        costoVaria = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        utilidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        viajesSemanales = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        totalPasajeros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        viajesNSemanales = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ganarMensual = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalMargen = new javax.swing.JTextField();
        botonCalcularP = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        totalNMargen = new javax.swing.JTextField();
        totalNPasajeros = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ejercicio 6");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 160, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 0, 40, 40);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 40);

        jToolBar1.setRollover(true);

        botonAbrirArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abrirPDF.png"))); // NOI18N
        botonAbrirArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAbrirArchivo.setFocusable(false);
        botonAbrirArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAbrirArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAbrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAbrirArchivoMouseClicked(evt);
            }
        });
        jToolBar1.add(botonAbrirArchivo);

        verFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        verFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verFormulario.setFocusable(false);
        verFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verFormulario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verFormulario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                verFormularioItemStateChanged(evt);
            }
        });
        jToolBar1.add(verFormulario);

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.setFocusable(false);
        botonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonEditar);

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrar.setFocusable(false);
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBorrarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonBorrar);

        botonInicializar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar.png"))); // NOI18N
        botonInicializar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicializar.setFocusable(false);
        botonInicializar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonInicializar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonInicializar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicializarMouseClicked(evt);
            }
        });
        jToolBar1.add(botonInicializar);

        botonCalcularS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calcular.png"))); // NOI18N
        botonCalcularS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcularS.setFocusable(false);
        botonCalcularS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCalcularS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCalcularS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCalcularSMouseClicked(evt);
            }
        });
        jToolBar1.add(botonCalcularS);

        add(jToolBar1);
        jToolBar1.setBounds(0, 40, 730, 30);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(0, 430, 730, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Compañia turistica");
        add(jLabel3);
        jLabel3.setBounds(0, 74, 730, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Costo sueldo y gasolina:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 0, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Otros costos fijos:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, 30, 160, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 160, 60);

        costoSueldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        costoSueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        costoSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoSueldoKeyTyped(evt);
            }
        });
        jPanel3.add(costoSueldo);
        costoSueldo.setBounds(160, 0, 140, 30);

        costosFijos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        costosFijos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        costosFijos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costosFijosKeyTyped(evt);
            }
        });
        jPanel3.add(costosFijos);
        costosFijos.setBounds(160, 30, 140, 30);

        add(jPanel3);
        jPanel3.setBounds(50, 120, 300, 60);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tarifa unica:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel7);
        jLabel7.setBounds(0, 0, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Costos variables:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel8);
        jLabel8.setBounds(0, 30, 160, 30);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, 0, 160, 60);

        tarifaUnica.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tarifaUnica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tarifaUnica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tarifaUnicaKeyTyped(evt);
            }
        });
        jPanel6.add(tarifaUnica);
        tarifaUnica.setBounds(160, 0, 140, 30);

        costoVaria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        costoVaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        costoVaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoVariaKeyTyped(evt);
            }
        });
        jPanel6.add(costoVaria);
        costoVaria.setBounds(160, 30, 140, 30);

        add(jPanel6);
        jPanel6.setBounds(390, 120, 300, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("mensuales:");
        add(jLabel9);
        jLabel9.setBounds(580, 260, 80, 30);

        utilidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                utilidadKeyTyped(evt);
            }
        });
        add(utilidad);
        utilidad.setBounds(190, 260, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Margen Contribucion:");
        add(jLabel10);
        jLabel10.setBounds(390, 310, 140, 30);

        viajesSemanales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                viajesSemanalesKeyTyped(evt);
            }
        });
        add(viajesSemanales);
        viajesSemanales.setBounds(170, 210, 100, 30);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("$");
        add(jLabel23);
        jLabel23.setBounds(460, 260, 20, 30);

        totalPasajeros.setBackground(new java.awt.Color(255, 255, 0));
        totalPasajeros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalPasajeros);
        totalPasajeros.setBounds(50, 360, 120, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pasajeros");
        add(jLabel4);
        jLabel4.setBounds(600, 360, 60, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Viajes semanales:");
        add(jLabel11);
        jLabel11.setBounds(50, 210, 120, 30);

        viajesNSemanales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                viajesNSemanalesKeyTyped(evt);
            }
        });
        add(viajesNSemanales);
        viajesNSemanales.setBounds(560, 210, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Nuevos viajes semanales:");
        add(jLabel12);
        jLabel12.setBounds(390, 210, 160, 30);

        ganarMensual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ganarMensualKeyTyped(evt);
            }
        });
        add(ganarMensual);
        ganarMensual.setBounds(480, 260, 100, 30);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("$");
        add(jLabel24);
        jLabel24.setBounds(170, 260, 20, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Para ganar");
        add(jLabel13);
        jLabel13.setBounds(390, 260, 70, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Utilidad a obtener:");
        add(jLabel14);
        jLabel14.setBounds(50, 260, 120, 30);

        totalMargen.setBackground(new java.awt.Color(255, 255, 0));
        totalMargen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalMargen);
        totalMargen.setBounds(190, 310, 100, 30);

        botonCalcularP.setBackground(new java.awt.Color(0, 153, 153));
        botonCalcularP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonCalcularP.setForeground(new java.awt.Color(255, 255, 255));
        botonCalcularP.setText("Calcular");
        botonCalcularP.setToolTipText("");
        botonCalcularP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCalcularP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCalcularPMouseClicked(evt);
            }
        });
        add(botonCalcularP);
        botonCalcularP.setBounds(310, 380, 110, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Margen Contribucion:");
        add(jLabel15);
        jLabel15.setBounds(50, 310, 140, 30);

        totalNMargen.setBackground(new java.awt.Color(255, 255, 0));
        totalNMargen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalNMargen);
        totalNMargen.setBounds(530, 310, 100, 30);

        totalNPasajeros.setBackground(new java.awt.Color(255, 255, 0));
        totalNPasajeros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(totalNPasajeros);
        totalNPasajeros.setBounds(500, 360, 100, 30);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Pasajeros");
        add(jLabel16);
        jLabel16.setBounds(170, 360, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirArchivoMouseClicked
        try
        {
            //Creamos un archivo en la carpeta temporal de tu sistema operativo
            File temp = new File(System.getProperty("java.io.tmpdir") + "Ejercicios.pdf");
            
            //Creamos un flujo de entrada al cual asignamos el valor del PDF que esta dentro del JAR
            InputStream flujoEntrada = this.getClass().getResourceAsStream("/Archivos/Ejercicios_del_sistema.pdf");
            
            //Creamos un flujo de salida para poder escribir sobre el archivo temporal
            FileOutputStream flujoSalida = new FileOutputStream(temp);
            //Preparamos el temp para que se llene de la informacion de PDF dentro del jar
            FileWriter fw = new FileWriter(temp);
            //Creamos un arreglo de bytes generico que soporte un gran tamano 1KB * 512 B --> se usa para todo tipo de archivo  
            byte[] buffer = new byte[1024*512];
 
            int control; //para contar posiciones de byte
 
            //Mientras haya bytes por leer se ejecuta este bucle
            while ((control = flujoEntrada.read(buffer)) != -1){
                flujoSalida.write(buffer, 0, control);
            }
 
            //Cerramos y guardamos el archivo creado
            fw.close();
            flujoSalida.close();
            flujoEntrada.close();
 
            //Ahora ya tenemos en temp todo tu PDF descomprimido y lo podemos abrir
            Desktop.getDesktop().open(temp);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Existe un error: " + e,"Ejercicios pdf", 2);
        }
    }//GEN-LAST:event_botonAbrirArchivoMouseClicked

    private void verFormularioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_verFormularioItemStateChanged
        if(verFormulario.isSelected())
        {
            vf.setVisible(true);
        }
        else
        {
            vf.dispose();
        }
    }//GEN-LAST:event_verFormularioItemStateChanged

    private void costoSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoSueldoKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && costoSueldo.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_costoSueldoKeyTyped

    private void costosFijosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costosFijosKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && costosFijos.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_costosFijosKeyTyped

    private void tarifaUnicaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tarifaUnicaKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && tarifaUnica.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_tarifaUnicaKeyTyped

    private void costoVariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoVariaKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && costoVaria.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_costoVariaKeyTyped

    private void utilidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_utilidadKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && utilidad.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_utilidadKeyTyped

    private void ganarMensualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ganarMensualKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.'))
        evt.consume();

    if (c == '.' && ganarMensual.getText().contains("."))
        evt.consume();
    }//GEN-LAST:event_ganarMensualKeyTyped

    private void viajesSemanalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viajesSemanalesKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')))
        evt.consume();
    }//GEN-LAST:event_viajesSemanalesKeyTyped

    private void viajesNSemanalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viajesNSemanalesKeyTyped
    char c = evt.getKeyChar();
    
    if (((c < '0') || (c > '9')))
        evt.consume();
    }//GEN-LAST:event_viajesNSemanalesKeyTyped

    private void botonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseClicked
        setEditar();
        totalMargen.setText(null);
        totalNMargen.setText(null);
        totalPasajeros.setText(null);
        totalNPasajeros.setText(null);        
    }//GEN-LAST:event_botonEditarMouseClicked

    private void botonInicializarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicializarMouseClicked
        setBorrar();
        setInicializar();
        setBloquear();
    }//GEN-LAST:event_botonInicializarMouseClicked

    private void botonCalcularSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCalcularSMouseClicked
        if(costoSueldo.getText().equals("") || costosFijos.getText().equals("") || tarifaUnica.getText().equals("") ||
                costoVaria.getText().equals("") || viajesSemanales.getText().equals("") || viajesNSemanales.getText().equals("")
                || utilidad.getText().equals("") || ganarMensual.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Se han detectado valores nulos \n","Verifique los datos ingresados", 0);
        else
        {
            try
            {
                setA();
                setB();
                setBloquear();  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error, se han detectado valores nulos: \n" + e ,"Verifique los datos ingresados", 0);
            }
        }            
    }//GEN-LAST:event_botonCalcularSMouseClicked

    private void botonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMouseClicked
        setBorrar();
        setBloquear();
    }//GEN-LAST:event_botonBorrarMouseClicked

    private void botonCalcularPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCalcularPMouseClicked
        if(costoSueldo.getText().equals("") || costosFijos.getText().equals("") || tarifaUnica.getText().equals("") ||
                costoVaria.getText().equals("") || viajesSemanales.getText().equals("") || viajesNSemanales.getText().equals("")
                || utilidad.getText().equals("") || ganarMensual.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Se han detectado valores nulos \n","Verifique los datos ingresados", 0);
        else
        {
            try
            {
                setA();
                setB();
                setBloquear();  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Ha ocurrido un error, se han detectado valores nulos: \n" + e ,"Verifique los datos ingresados", 0);
            }
        }    
    }//GEN-LAST:event_botonCalcularPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbrirArchivo;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCalcularP;
    private javax.swing.JButton botonCalcularS;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonInicializar;
    private javax.swing.JTextField costoSueldo;
    private javax.swing.JTextField costoVaria;
    private javax.swing.JTextField costosFijos;
    private javax.swing.JTextField ganarMensual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField tarifaUnica;
    private javax.swing.JTextField totalMargen;
    private javax.swing.JTextField totalNMargen;
    private javax.swing.JTextField totalNPasajeros;
    private javax.swing.JTextField totalPasajeros;
    private javax.swing.JTextField utilidad;
    private javax.swing.JToggleButton verFormulario;
    private javax.swing.JTextField viajesNSemanales;
    private javax.swing.JTextField viajesSemanales;
    // End of variables declaration//GEN-END:variables
    GetOperaciones gop;
    private VentanaFormulario vf;
    NumberFormat formatoImporte;
    NumberFormat formatoNumero;    
}
